eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8776
spring:
  application:
    name: my-schedule
  datasource:
    url:  jdbc:mysql://localhost:3306/quartz?useSSL=false
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mapper/*.xml
